# Generated by Django 4.0.5 on 2022-06-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('pnombre', models.CharField(max_length=25, verbose_name='Primer Nombre')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellido')),
                ('email', models.CharField(max_length=25, verbose_name='Email')),
                ('contraseña', models.CharField(max_length=25, verbose_name='Contraseña')),
                ('rut', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='RUT')),
                ('telefono', models.CharField(max_length=25, verbose_name='Teléfono')),
                ('Direccion', models.CharField(max_length=25, verbose_name='Dirección')),
                ('region', models.CharField(max_length=25, verbose_name='Región')),
                ('comuna', models.CharField(max_length=25, verbose_name='Comuna')),
            ],
        ),
    ]
