# Generated by Django 4.0.5 on 2022-06-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Direccion',
            field=models.CharField(max_length=50, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='comuna',
            field=models.CharField(max_length=50, verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=50, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pnombre',
            field=models.CharField(max_length=50, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='region',
            field=models.CharField(max_length=50, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=50, verbose_name='Teléfono'),
        ),
    ]
